# -*- coding: utf-8 -*-
"""app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FTRGQOSAV5kcP0tW1PZjon6QeKRLoyIb
"""

from google.colab import drive
drive.mount('/content/gdrive')

!pip install flask-ngrok

from flask_ngrok import run_with_ngrok
from flask import Flask, render_template , request, url_for, redirect
import gensim
from gensim.summarization import summarize

import os

##Running the flask app
app = Flask(__name__, template_folder='/content/gdrive/MyDrive/Project_Algorhythm_Summarizer/templates')

#start ngrok when app is run
run_with_ngrok(app)

def summarizer(text):
  summary=summarize(text, ratio=0.1, word_count=100) #both, but follows number of words
  return str(summary)

@app.route("/", methods=["GET","POST"])
def home():

  request_method = request.method
  if request.method == 'POST':
    book_title = request.form["book_title"]
    full_text = str(book_title)
    summary = summarizer(book_title)
    return render_template('summary.html', summary = summary, full_text = full_text)
  return render_template("index.html", request_method=request_method)


if __name__ == '__main__':
  app.run()

